numerical_columns:
- Census_ProcessorCoreCount
- Census_PrimaryDiskTotalCapacity
- Census_SystemVolumeTotalCapacity
- Census_TotalPhysicalRAM
- Census_InternalPrimaryDiagonalDisplaySizeInInches
- Census_InternalPrimaryDisplayResolutionHorizontal
- Census_InternalPrimaryDisplayResolutionVertical
- Census_InternalBatteryNumberOfCharges
- AVProductsInstalled

drop_columns:
- MachineIdentifier