row_data_columns:
  MachineIdentifier: str
  ProductName: str
  EngineVersion: str
  AppVersion: str
  AvSigVersion: str
  IsBeta: int
  RtpStateBitfield: float
  IsSxsPassiveMode: int
  DefaultBrowsersIdentifier: float
  AVProductStatesIdentifier: float
  AVProductsInstalled: float
  AVProductsEnabled: float
  HasTpm: int
  CountryIdentifier: int
  CityIdentifier: float
  OrganizationIdentifier: float
  GeoNameIdentifier: int
  LocaleEnglishNameIdentifier: int
  Platform: str
  Processor: str
  OsVer: str
  OsBuild: int
  OsSuite: int
  OsPlatformSubRelease: str
  OsBuildLab: str
  SkuEdition: str
  IsProtected: float
  AutoSampleOptIn: int
  PuaMode: str
  SMode: float
  IeVerIdentifier: float
  SmartScreen: str
  Firewall: float
  UacLuaenable: float
  Census_MDC2FormFactor: str
  Census_DeviceFamily: str
  Census_OEMNameIdentifier: float
  Census_OEMModelIdentifier: float
  Census_ProcessorCoreCount: float
  Census_ProcessorManufacturerIdentifier: float
  Census_ProcessorModelIdentifier: float
  Census_ProcessorClass: str
  Census_PrimaryDiskTotalCapacity: float
  Census_PrimaryDiskTypeName: str
  Census_SystemVolumeTotalCapacity: float
  Census_HasOpticalDiskDrive: int
  Census_TotalPhysicalRAM: float
  Census_ChassisTypeName: str
  Census_InternalPrimaryDiagonalDisplaySizeInInches: float
  Census_InternalPrimaryDisplayResolutionHorizontal: float
  Census_InternalPrimaryDisplayResolutionVertical: float
  Census_PowerPlatformRoleName: str
  Census_InternalBatteryType: str
  Census_InternalBatteryNumberOfCharges: float
  Census_OSVersion: str
  Census_OSArchitecture: str
  Census_OSBranch: str
  Census_OSBuildNumber: int
  Census_OSBuildRevision: int
  Census_OSEdition: str
  Census_OSSkuName: str
  Census_OSInstallTypeName: str
  Census_OSInstallLanguageIdentifier: float
  Census_OSUILocaleIdentifier: int
  Census_OSWUAutoUpdateOptionsName: str
  Census_IsPortableOperatingSystem: int
  Census_GenuineStateName: str
  Census_ActivationChannel: str
  Census_IsFlightingInternal: float
  Census_IsFlightsDisabled: float
  Census_FlightRing: str
  Census_ThresholdOptIn: float
  Census_FirmwareManufacturerIdentifier: float
  Census_FirmwareVersionIdentifier: float
  Census_IsSecureBootEnabled: int
  Census_IsWIMBootEnabled: float
  Census_IsVirtualDevice: float
  Census_IsTouchEnabled: int
  Census_IsPenCapable: int
  Census_IsAlwaysOnAlwaysConnectedCapable: float
  Wdft_IsGamer: float
  Wdft_RegionIdentifier: float
  HasDetections: int

drop_columns_eda:
- MachineIdentifier
- DefaultBrowsersIdentifier
- PuaMode
- Census_ProcessorClass
- Census_InternalBatteryType
- Census_IsFlightingInternal
- Census_ThresholdOptIn
- Census_IsWIMBootEnabled
- ProductName
- IsBeta
- IsSxsPassiveMode
- AVProductsEnabled
- Platform
- OsVer
- IsProtected
- SMode
- Firewall
- Census_DeviceFamily
- Census_ProcessorManufacturerIdentifier
- Census_HasOpticalDiskDrive
- Census_OSArchitecture
- Census_IsPortableOperatingSystem
- Census_IsFlightsDisabled
- Census_IsVirtualDevice
- Census_IsPenCapable

binary_columns:
- Processor
- Census_IsSecureBootEnabled
- Census_IsTouchEnabled
- Census_IsAlwaysOnAlwaysConnectedCapable
- Wdft_IsGamer


categorical_columns:
- Processor
- Census_IsSecureBootEnabled
- Census_IsTouchEnabled
- Census_IsAlwaysOnAlwaysConnectedCapable
- Wdft_IsGamer
- RtpStateBitfield
- OsBuild
- OsSuite
- OsPlatformSubRelease
- SkuEdition
- SmartScreen
- Census_MDC2FormFactor
- Census_PrimaryDiskTypeName
- Census_ChassisTypeName
- Census_PowerPlatformRoleName
- Census_OSBranch
- Census_OSBuildNumber
- Census_OSEdition
- Census_OSSkuName
- Census_OSInstallTypeName
- Census_OSWUAutoUpdateOptionsName
- Census_ActivationChannel
- Wdft_RegionIdentifier
- EngineVersion_2
- EngineVersion_3
- OsBuildLab_0
- OsBuildLab_2
- OsBuildLab_3
- Census_OSVersion_0
- Census_OSVersion_1
- Census_OSVersion_2


frequency_columns:
- AvSigVersion
- AVProductStatesIdentifier
- CountryIdentifier
- OrganizationIdentifier
- GeoNameIdentifier
- LocaleEnglishNameIdentifier
- IeVerIdentifier
- Census_OEMNameIdentifier
- Census_OEMModelIdentifier
- Census_ProcessorModelIdentifier
- Census_OSBuildRevision
- Census_OSInstallLanguageIdentifier
- Census_OSUILocaleIdentifier
- Census_FirmwareManufacturerIdentifier
- Census_FirmwareVersionIdentifier
- OsBuildLab_1
- Census_OSVersion_3

numerical_columns:
- Census_ProcessorCoreCount
- Census_PrimaryDiskTotalCapacity
- Census_SystemVolumeTotalCapacity
- Census_TotalPhysicalRAM
- Census_InternalBatteryNumberOfCharges
- AVProductsInstalled


drop_columns_stats:
- EngineVersion
- AppVersion
- CityIdentifier
- OsBuildLab
- Census_OSVersion
- Census_InternalPrimaryDisplayResolutionHorizontal
- Census_InternalPrimaryDisplayResolutionVertical
- Census_InternalPrimaryDiagonalDisplaySizeInInches
- AutoSampleOptIn
- UacLuaenable
- Census_GenuineStateName
- Census_FlightRing
- HasTpm


target_column:
- HasDetections


model_config:
  learning_rate: 0.05
  max_depth: 10
  min_child_samples: 25
  n_jobs: -1
  num_leaves: 300
  reg_alpha: 0
  colsample_bytree: 0.6
  n_estimators: 500
